# Site settings
title: DT Tribal Knowledge
description: Knowledge sharing for the tech tribe
email: aly.simkins@dialogtech.com
github_username:  alysonmichele
url: https://gituniverse-ci-cd.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
